language: go
sudo: false

go:
    - "1.13"

install:
    - go get -u github.com/Masterminds/glide
    - go get -u -v golang.org/x/lint/golint
    - go get -u github.com/mattn/goveralls

script:
    - make all check
    - $HOME/gopath/bin/goveralls -coverprofile=build/cover.out -service=travis-ci
