language: go
sudo: false

go:
    - 1.14
    - 1.15

install:
    - go get -u -v golang.org/x/lint/golint
    - go get -u github.com/mattn/goveralls

script:
    - make all check
    - $HOME/gopath/bin/goveralls -coverprofile=build/cover.out -service=travis-ci
