# SPDX-FileCopyrightText: SAP SE
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  ".github/assets/hermes.png",
  "AppStructure.png",
  "docs/example-policy.json",
  "etc/permissive-policy.json",
  "etc/policy.json",
  "pkg/api/fixtures/*.json",
  "pkg/test/policy.json",
  "go.sum",
  "build/.empty.txt",
  "etc/*.conf",
]
SPDX-FileCopyrightText = "SAP SE"
SPDX-License-Identifier = "Apache-2.0"
