name: License
"on":
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '**.md'
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
jobs:
  addlicense:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.17"
    - name: Check if source code files have license header
      run: |
        go install github.com/google/addlicense@latest
        find * \( -name vendor -type d -prune \) -o \( -name \*.go -exec addlicense --check -- {} + \)
