name: Spell
"on":
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master
jobs:
  misspell:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Check for spelling errors
      uses: reviewdog/action-misspell@v1
      with:
        exclude: ./vendor/*
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
